# Generated by Django 2.2 on 2021-06-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechVrDev', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechVrDev',
            new_name='TechVrDevapp',
        ),
    ]
